require 'rubygems'
require 'rack'
require 'json'
require 'net/http'
require 'uri'
require 'rack/app'
require 'erb'
require 'rack/app/front_end'
require 'bootstrap-sass'
require 'pry'

require_relative './lib/server/TemplateMessenger'
require_relative './lib/server/MessageBuilder'
require_relative './lib/server/TemplateBuilder'
require_relative './lib/server/FileOperator'
require_relative './lib/server/template'
require_relative './lib/server/send_message'
ROOT_PATH = Dir.pwd + '/lib/server/templates'