FROM ruby:2.4.0-alpine

RUN apk add --no-cache alpine-sdk postgresql-dev git

# Clone web-application
RUN git clone https://github.com/KarambaKG/rack-app.git

RUN gem install bundler

RUN cd rack-app && bundle

WORKDIR /rack-app

RUN echo "I am ready!!!"
